### ISSUE TITLE
Nodewar 1.2.0 not working, and i get bugs on console.

### ISSUE THREAD

**Issue by Ethon6** [Rosstail/Nodewar#1]
I use: JDK 17, Spigot 1.18.1, worldedit-bukkit-7.2.9., worldguard-bukkit-7.0.7-SNAPSHOT-dist. 

On Join Error:

![image](https://user-images.githubusercontent.com/19668243/152935640-2a5a3564-d7b8-40bf-bd1c-ef5fdfb7c41a.png)

On Quit Error:

![image](https://user-images.githubusercontent.com/19668243/152935524-a693a420-9480-40b6-9ef5-cc42693131bb.png)

On moving a region:

![image](https://user-images.githubusercontent.com/19668243/152935700-649dddcc-f62e-402e-941c-11bfe455f42c.png)

**Comment by Rosstail** [comment]
Alright, it seems there is a problem on loading players data from flat files, the SQL don't have this kind of error, I'll fix it asap.

For the regions, I'll check with your territory files soon.

**Comment by Rosstail** [comment]
After checking your files, the error comes from a misconfiguration of territories/points. I'll replace these repeating error messages for a single error message on first error with the reason of error written on it.

**Comment by Rosstail** [comment]
After discussion on discord server, the error seems to be fixed with a test version.
