### ISSUE TITLE
When i invade a capturable point, it's not start capture, and i get console error.

### ISSUE THREAD

**Issue by Ethon6** [Rosstail/Nodewar#3]
![image](https://user-images.githubusercontent.com/19668243/153083642-f4ee3c14-675e-414a-bc40-c6fe078d6940.png)

![image](https://user-images.githubusercontent.com/19668243/153084088-6e3e4416-f4b7-443a-9f4b-05001bdc7c59.png)

**Comment by Rosstail** [comment]
After discussion on discord server, the error seems to be fixed with a test version.
